// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhlvC8FlcbHYPv0LBRdyDEg6AAzTUCCnA',
    appId: '1:641706813756:web:140ab2299029d48aee1639',
    messagingSenderId: '641706813756',
    projectId: 'flutterlatihan-94e65',
    authDomain: 'flutterlatihan-94e65.firebaseapp.com',
    storageBucket: 'flutterlatihan-94e65.appspot.com',
    measurementId: 'G-LE84Z06TRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyxKyJjbbYpZPbcleXaV2YmM21WwKEQRU',
    appId: '1:641706813756:android:d01fdf7c886d972dee1639',
    messagingSenderId: '641706813756',
    projectId: 'flutterlatihan-94e65',
    storageBucket: 'flutterlatihan-94e65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4pXs_D-U8G2Fih9obgsh8PFDnSXvKipU',
    appId: '1:641706813756:ios:88f442d2de49bdb1ee1639',
    messagingSenderId: '641706813756',
    projectId: 'flutterlatihan-94e65',
    storageBucket: 'flutterlatihan-94e65.appspot.com',
    iosBundleId: 'com.example.flutterlatihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4pXs_D-U8G2Fih9obgsh8PFDnSXvKipU',
    appId: '1:641706813756:ios:cd96aba6202dab10ee1639',
    messagingSenderId: '641706813756',
    projectId: 'flutterlatihan-94e65',
    storageBucket: 'flutterlatihan-94e65.appspot.com',
    iosBundleId: 'com.example.flutterlatihan.RunnerTests',
  );
}
